name: test
on:
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test:
    name: test
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
