name: test
on:
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Remove cargo
        run: |
          rm -rf ~/.cargo
          rm -rf ~/.rustup
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.86.0
      - uses: jdx/mise-action@v3
