name: test
on:
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Remove cargo
        run: cargo --version
      - uses: jdx/mise-action@v3
